version: '3'
services:
  jim:
    container_name: jim-container
    image: docerizationalization-jim
    ports:
      - "8081:8081"
    networks:
      - my-network
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  beam:
    container_name: beam-container
    image: docerizationalization-beam
    ports:
      - "8082:8082"
    networks:
      - my-network
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  eureka-server:
    image: docerizationalization-eureka
    container_name: eureka-container
    ports:
      - "8761:8761"
    networks:
      - my-network
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  api-gateway:
    image: docerizationalization-gateway
    container_name: gateway-container
    ports:
      - "8091:8091"
    networks:
      - my-network
    depends_on:
      - eureka-server
    environment:
      - SPRING_PROFILES_ACTIVE=docker

networks:
  my-network:
    driver: bridge