server:
  port: 8091

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: jim-id
          uri: lb://jim
          predicates:
            - Path=/jim/**
        - id: beam-id
          uri: lb://beam
          predicates:
            - Path=/beam/**
    loadbalancer:
      enabled: true
      strategy: RoundRobin
      health-check:
        enabled: true
        interval: 5s # Set a lower health check interval
        timeout: 2s  # Set a lower health check timeout

management:
  tracing:
    sampling:
      #capture all traces that will be generated
      probability: 1.0
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
          - metrics

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
      #defaultZone: http://localhost:8761/eureka
      #defaultZone: http://192.168.0.234:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true