server:
  port: 8081

spring:
  application:
    name: jim
  cloud:
    loadbalancer:
      health-check:
        enabled: true
        interval: 5s
        timeout: 2s

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include:
          - prometheus
          - health
          - metrics

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true